export const imageFilmsUrls: { [key: string]: string } = {
    "A New Hope": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/a-new-hope.jpg",
    "The Empire Strikes Back": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/the-empire-strikes-back.jpg",
    "Return of the Jedi": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891707/starwars/return-of-the-jedi.jpg",
    "The Phantom Menace": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/the-phantom-menace.png",
    "Attack of the Clones": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/attack-of-the-clones.jpg",
    "Revenge of the Sith": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/revenge-of-the-sith.jpg",
};


export const imageCharacterUrls: { [key: string]: string } = {
    "Luke Skywalker": "",
    "C-3PO": "",
    "R2-D2": "",
    "Darth Vader": "",
    "Leia Organa": "",
    "Owens Lars": "",
    "Beru Whitesun lars": "",
    "R5-D4": "",
    "Biggs Darklighter": "",
    "Obi-Wan Kenobi": "",
    "Wilhuff Tarkin": "",
    "Chewbacca": "",
    "Han Solo": "",
    "Greedo": "",
    "Jabba Desilijic Tiure": "",
    "Wedge Antilles": "",
    "Jek Tono Porkins": "",
    "Raymus Antilles": "",
    "Yoda": "",
    "Palpatine": "",
    "Boba Fett": "",
    "IG-88": "",
    "Bossk": "",
    "Lando Calrissian": "",
    "Lobot": "",
    "Ackbar": "",
    "Mon Mothma": "",
    "Arvel Crynyd": "",
    "Wicket Systri Warrick": "",
    "Nien Nunb": "",
    "Bib Fortuna": "",
    "Anakin Skywalker": "",
    "Qui-Gon Jinn": "",
    "Nute Gunray": "",
    "Finis Valorum": "",
    "Padmé Amidala": "",
    "Jar Jar Binks": "",
    "Roos Tarpals": "",
    "Rugor Nass": "",
    "Ric Olié": "",
    "Watto": "",
    "Sebulba": "",
    "Quarsh Panaka": "",
    "Shmi Skywalker": "",
    "Darth Maul": "",
    "Ayla Secura": "",
    "Ratts Tyerel": "",
    "Dud Bolt": "",
    "Gasgano": "",
    "Ben Quadinaros": "",
    "Mace Windu": "",
    "Ki-Adi-Mundi": "",
    "Kit Fisto": "",
    "Eeth Koth": "",
    "Adi Gallia": "",
    "Saesee Tiin": "",
    "Yarael Poof": "",
    "Plo Koon": "",
    "Mas Amedda": "",
    "Gregar Typho": "",
    "Cordé": "",
    "Cliegg Lars": "",
    "Poggle the Lesser": "",
    "Luminara Unduli": "",
    "Barriss Offee": "",
    "Dormé": "",
    "Dooku": "",
    "Bail Prestor Organa": "",
    "Jango Fett": "",
    "Zam Wesell": "",
    "Dexter Jettster": "",
    "Lama Su": "",
    "Taun We": "",
    "Jocasta Nu": "",
    "R4-P17": "",
    "Wat Tambor": "",
    "San Hill": "",
    "Shaak Ti": "",
    "Sly Moore": "",
    "Grievous": "",
    "Tarfful": "",
    "Tion Medon": ""
};