export const imageFilmsUrls: { [key: string]: string } = {
    "A New Hope": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/a-new-hope.jpg",
    "The Empire Strikes Back": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/the-empire-strikes-back.jpg",
    "Return of the Jedi": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891707/starwars/return-of-the-jedi.jpg",
    "The Phantom Menace": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/the-phantom-menace.png",
    "Attack of the Clones": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/attack-of-the-clones.jpg",
    "Revenge of the Sith": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725891706/starwars/revenge-of-the-sith.jpg",
};


export const imageCharacterUrls: { [key: string]: string } = {
    "Luke Skywalker": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/luke-skywalker.jpg",
    "C-3PO": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/c-3po.jpg",
    "R2-D2": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/r2-d2.jpg",
    "Darth Vader": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/darth-vader.jpg",
    "Leia Organa": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/leia-organa.jpg",
    "Owen Lars": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/owen-lars.jpg",
    "Beru Whitesun lars": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/beru-whitesun-lars.jpg",
    "R5-D4": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980791/starwars/characters/r5-d4.jpg",
    "Biggs Darklighter": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980790/starwars/characters/biggs-darklighter.jpg",
    "Obi-Wan Kenobi": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980790/starwars/characters/obiwan-kenobi.jpg",
    "Wilhuff Tarkin": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980790/starwars/characters/wilhuff-tarkin.jpg",
    "Chewbacca": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980790/starwars/characters/chewbacca.jpg",
    "Han Solo": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980790/starwars/characters/han-solo.jpg",
    "Greedo": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980789/starwars/characters/greedo.jpg",
    "Jabba Desilijic Tiure": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980789/starwars/characters/jabba.jpg",
    "Wedge Antilles": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980790/starwars/characters/wedge-antilles.jpg",
    "Jek Tono Porkins": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725980789/starwars/characters/jek-tono-porkins.webp",
    "Raymus Antilles": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/raymus-antilles.webp",
    "Yoda": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/yoda.webp",
    "Palpatine": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/palpatine.jpg",
    "Boba Fett": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/boba-fett.jpg",
    "IG-88": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/ig-88.webp",
    "Bossk": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/bossk.webp",
    "Lando Calrissian": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/lando-calrissian.webp",
    "Lobot": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/lobot.webp",
    "Ackbar": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/ackbar.jpg",
    "Mon Mothma": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/mon-mothma.webp",
    "Arvel Crynyd": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981620/starwars/characters/arvel-crynyd.webp",
    "Wicket Systri Warrick": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981621/starwars/characters/wicket-systri-warrick.webp",
    "Nien Nunb": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981621/starwars/characters/nien-nunb.webp",
    "Bib Fortuna": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/bib-fortuna.webp",
    "Anakin Skywalker": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/anakin-skywalker.webp",
    "Qui-Gon Jinn": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/qui-gon-jinn.jpg",
    "Nute Gunray": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/nute-gunray.webp",
    "Finis Valorum": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/finis-valorum.webp",
    "Padmé Amidala": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/padme-amidala.webp",
    "Jar Jar Binks": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981618/starwars/characters/jar-jar-binks.webp",
    "Roos Tarpals": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/roos-tarpals.webp",
    "Rugor Nass": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/rugor-nass.webp",
    "Ric Olié": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/ric-olie.webp",
    "Watto": "https://res.cloudinary.com/dvvtskcux/image/upload/v1725981619/starwars/characters/watto.webp",
    "Sebulba": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065424/starwars/characters/sebulba.webp",
    "Quarsh Panaka": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065422/starwars/characters/quarsh-panaka.webp",
    "Shmi Skywalker": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/shmi-skywalker.webp",
    "Darth Maul": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065422/starwars/characters/darth-maul.webp",
    "Ayla Secura": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065422/starwars/characters/ayla-secura.webp",
    "Ratts Tyerel": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065422/starwars/characters/ratts-tyerel.jpg",
    "Dud Bolt": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065424/starwars/characters/dud-bolt.webp",
    "Gasgano": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065424/starwars/characters/gasgano.jpg",
    "Ben Quadinaros": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/ben-quadinaros.webp",
    "Mace Windu": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/mace-windu.webp",
    "Ki-Adi-Mundi": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/ki-adi-mundi.webp",
    "Kit Fisto": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065422/starwars/characters/kit-fisto.webp",
    "Eeth Koth": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065424/starwars/characters/eeth-koth.webp",
    "Adi Gallia": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/adi-gallia.webp",
    "Saesee Tiin": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/saesee-tiin.jpg",
    "Yarael Poof": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/yarael-poof.webp",
    "Plo Koon": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726065423/starwars/characters/plo-koon.webp",
    "Mas Amedda": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/mas-amedda.webp",
    "Gregar Typho": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066226/starwars/characters/gregar-typho.webp",
    "Cordé": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/corde.webp",
    "Cliegg Lars": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066226/starwars/characters/cliegg-lars.webp",
    "Poggle the Lesser": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066229/starwars/characters/poggle-the-lesser.webp",
    "Luminara Unduli": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/luminara-unduli.webp",
    "Barriss Offee": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066229/starwars/characters/barriss-offee.webp",
    "Dormé": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/dorme.webp",
    "Dooku": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/doku.webp",
    "Bail Prestor Organa": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/bail-prestor-organa.webp",
    "Jango Fett": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/jango-fett.jpg",
    "Zam Wesell": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/zam-wesell.webp",
    "Dexter Jettster": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/dexter-jettster.webp",
    "Lama Su": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066228/starwars/characters/lama-su.webp",
    "Taun We": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/taun-we.webp",
    "Jocasta Nu": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/jocasta-nu.webp",
    "R4-P17": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/r4-p17.jpg",
    "Wat Tambor": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/wat-tambor.avif",
    "San Hill": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/san-hill.webp",
    "Shaak Ti": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066640/starwars/characters/shaak-ti.webp",
    "Sly Moore": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/sly-moore.webp",
    "Grievous": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/grievous.webp",
    "Tarfful": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066227/starwars/characters/tarfful.webp",
    "Tion Medon": "https://res.cloudinary.com/dvvtskcux/image/upload/v1726066226/starwars/characters/tion-medon.webp"
};